---
- name: Install Nginx, PHP-FPM, Mariadb, Wordpress, New Relic and Secure the system
  hosts: webserver
  user: user
  become: yes
  vars:
    ansible_become_pass: Password
  roles:
    - common
    - nginx
    - php-fpm
    - mariadb
    - wordpress
    - secure_db
    - newrelic
